logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}] [%X{ddd:-},%X{bp:-},%X{bpids:-}] [%X{op:-},%X{chunk:-},%X{i:-}]\n"

spring:
  application:
    name: PROFILENOTSET
  #main:
  #  allow-bean-definition-overriding: true
  jmx:
    enabled: false
  sleuth:
    opentracing:
      enabled: true
    sampler:
      probability: 1.0
    annotation:
      enabled: true
    # keys that travel with inter-process calls (see MDCLocal.java)
    # these keys will be prefix by "baggage-" (if http) or "baggage_" (if messaging)
    baggage-keys:
    - bpids
    - ddd
    - bp
    local-keys: # keys that are only propagated within the app
    - op
    - chunk
    - i
    # keys that travel with inter-process calls (see MDCLocal.java)
    # these keys will not be prefixed
    propagation-keys: # keys propagated to zipkin
    log:
      slf4j:
        whitelisted-mdc-keys: # (baggage|propagation)-keys that are copied to slf4j MDC
        - bpids
        - ddd
        - bp
        - op
        - chunk
        - i

---

spring:
  profiles: sender
  application:
    name: sender

server:
  port: 8080

---

spring:
  profiles: receiver
  application:
    name: receiver

server:
  port: 8081
 